### PR TITLE
change card member writer

### PR DESCRIPTION
**Pull request by aymhce**
Hello, there is a problem when group have more than one member. The group always keeps just one member despite that there are several. Therefore, this is a patch. It's works with Baikal/Sabredav 1.8.12. Thanks

### CODE REVIEW

**Comment by blind-coder** [comment]
Is still still an issue? I remember there were some changes to the handling of group members recently.

**Comment by adobo** [comment]
@blind-coder this is still an issue. #170 includes a proposed change to make it work as expected.

**Comment by aymhce** [comment]
Ok I have merged the proposed change from #170

**Comment by blind-coder** [comment]
Thanks, I have (finally) merged this!

**Pull request merged**
