### PR TITLE
Add option for using categories of contacts as groups + small improvements

### PR DESCRIPTION
**Pull request by diorcety**
Some clients use categories as groups. this options allows to use in the groups in the same way

### CODE REVIEW

**Comment by Whoopie** [comment]
Any news on this? Would be great if the feature got merged. Thanks in advance!

**Comment by diorcety** [comment]
Hi,
From my side, i'm doing nothing more than i did. I provided my patches long time ago, more like a improvement request with a patch than a PR. I'm using it, i'm happy with it, i'm not going lost again few hours in order to rebase the PR, make conflict resolution, tests and pray for quick integration. Sorry

**Comment by blind-coder** [comment]
I'm sorry for neglecting this for so long.
I'm currently trying to fix the more critical showstopper issues, then release a new version and then I hope to get back to this.

**Comment by blind-coder** [comment]
I have just merged this into branch pr_6
It would be great if you could test this!

**Comment by sakanaou** [comment]
I just tried the pr_6 branch with owncloud 8.1 / contacts 0.4.0.0 and Roundcube 1.1.1. In theory it works - but the synched "group" is not visible in the adressbook pane. But each contact has a "group" tab where it is correctly marked if the contact belongs to that group or not. Don't know though where the problem is exactly.

**Comment by blind-coder** [comment]
@sakanaou I'm still on oc 8.0. Can you post a screenshot of that?

**Comment by sakanaou** [comment]
Here is a screenshot of the described issue.
carddav_group_issue


I also noticed in the carddav.warn log the following entry - maybe it is related:
`BACKEND: (get_record_from_carddav) Request for VCF 'D685D4E4-0301-47F9-96C8-6813EB13805F.vcf' which doesn't exist on the server.`

The Apache log shows for that
`"GET /remote.php/carddav/addressbooks/Daniel/contacts/D685D4E4-0301-47F9-96C8-6813EB13805F.vcf HTTP/1.1" 404 2577 "-" "RCM CardDAV plugin/1.0.0"`

**Comment by blind-coder** [comment]
Hmm, that's strange. It works fine here.

That error about the missing .vcf would indicate that you have contacts in your local cache of the addressbook that don't exist on the server. Can you please try either setting the refresh time to 0 or deleting and re-adding the addressbook in your settings? You need to do that anyway to be able to switch to the new CATEGORIES groups.

**Pull request merged**
