### PR TITLE
Updated installation procedure.

### PR DESCRIPTION
**Pull request by elmanytas**
Added step to load sql data in dbinit .

### CODE REVIEW

**Comment by blind-coder** [comment]
This should definately not be necessary, as the dbinit has been moved to dbmigrations/0000-dbinit/ and is executed the first time a user logs in to roundcube.
Did that not work for you?

**Comment by elmanytas** [comment]
No, it didn't work. I found a database error in any log so I saw the directory dbinit, looked for that tables in database and didn'f find them. So I executed

mysql -u root -p roundcubemail< dbinit/mysql.sql

and it began to work like a charm. You have done a very good work.
If it only happened to me maybe I did something wrong.

**Comment by blind-coder** [comment]
Did you migrate from an earlier version?
And can you paste the database errors you got?

**Comment by sesser** [comment]
FYI, I ran into the same issue with the database error after enabling this plugin. I also saw the `dbinit/mysql.sql` so I tried to import that into my database (which failed, BTW, on creating `carddav_users_groups`). Turns out, if you are currently logged into RC, this issue pops up. 

After seeing your comment about the database being updated/modified automagically, I dropped the `carddav_*` tables, cleared my session cookies for my RC site, and logged in again. Then everything went as planned.

That said, should probably make a note that you should not be logged in while installing this plugin.

**Comment by elmanytas** [comment]
I don't remember if I was or not loged in. sorry

But I think that if in the RC general plugin installation in http://trac.roundcube.net/wiki/Doc_Plugins does not say that we must be logged to install the plugin, in the plugin installation procedure must say it.

Do you agree with me?

**Comment by blind-coder** [comment]
I really need to delete the dbinit/ directory, it is not used anymore.
I agree, the INSTALL file must specify that the database is set up upon login ONLY. So logout, install plugin, log in is the process to use. Same goes for updating.

The reason behind that is that the check for database changes is only made upon login to prevent constant unnecessary database and filesystem access and processing delays.

**Comment by websafe** [comment]
@blind-coder :+1:

**Comment by blind-coder** [comment]
This change has been implemented in the meantime. Closing the PR.

**Pull request closed without merging**
