### PR TITLE
added password encryption with roundcube des_key

### PR DESCRIPTION
**Pull request by sahne123**
Hi there,

my first pull request ever \o/!

I thought it would be nice if we can store the password using the roundcube encryptition with the global des_key since this key is not supposed to be changed as the imap password. It might also be a good idea using this as default method.

### CODE REVIEW

**Comment by blind-coder** [comment]
Wow. I just have one of those "why didn't I think of that" moments.
Greta idea, I'll have a look at it!

**Comment by mstilkerich** [comment]
The problem is that once you have access to the roundcube server, you also have access to all the carddav passwords. It's not much better than BASE64 encoding, it just helps hiding the information from the well-behaved admin who may have a look at the database but doesn't *want* to see the passwords clear text. The imap password on the other hand is not stored on the server, and differs for each user. So you need one user's imap password to get that user's carddav password, but only one at a time because every password is encrypted with a different key. It's a feature, not a shortcoming.

**Comment by blind-coder** [comment]
@mstilkerich that's a valid point, using the IMAP password is obviously superior to using roundcubes des_key.
Bun in environments where database and mailserver administration differ in personnel and hardware/VM it's superior to base64.

**Comment by mstilkerich** [comment]
It's more about the roundcube server vs. the mysql server. If you only get access to the SQL server, then the DES key would be better than base64, however, if you gain access to the web server you will also have the credentials that roundcube uses to access the SQL server, and the roundcube DES key.

**Comment by sahne123** [comment]
I agree with @mstilkerich. But in my opinion it's always a better choice than base64 since you need the des_key. With base64 it's a problem if someone get only access to your DB or get access to an old Backup. Using the roundcube des_key you need Access to DB and the roundcube config.

- Most protective: using the imap password
- comfortable way if you change your password often and got multiple carddav accounts (less protective): using the des_key
- no real protection at all: base64/plain

**Comment by blind-coder** [comment]
I have merged this into a branch pr_105 and will test it within the next days.

**Pull request merged**
