### PR TITLE
Migration to composer

### PR DESCRIPTION
**Pull request by phsc**
- migration of included libraries to composer
- some clarifications in INSTALL

### CODE REVIEW

**Comment by phsc** [comment]
Successfully tested with Roundcube 1.1 and OwnCloud 6.

**Comment by blind-coder** [comment]
Can you clarify what composer is and how this will change the installation/update method?

**Comment by rumpelsepp** [comment]
A dependency manager, https://getcomposer.org/doc/00-intro.md

> Composer is a tool for dependency management in PHP. It allows you to declare the dependent libraries your project needs and it will install them in your project for you.

**Comment by phsc** [comment]
Composer is a dependency manager for PHP (see composer.org or packagist.org). It is really useful to keep the libraries up to date. The installation method for end users will not change.

The currently used version of sabre/vobject is quite outdated and because sabre/vobject requires the usage of composer since release 3.2, we have to switch to composer.

**Comment by blind-coder** [comment]
Looks pretty cool. I have never used it before, is it supposed to be used developer-side or end-user side?
If it helps keep the depending libs up-to-date I'm all for it, obviously, but I would like to keep rcmcarddav usable with a simple `git clone' and not have the enduser have to read a lengthy INSTALL document.

**Comment by phsc** [comment]
It is supposed to be used developer-side. You - the developer - has to run the required commands (composer install and composer update) and this will update your local repository. As soon as you push it to github, it will behave like before, which means, an end-user can use a git clone without further adjustements (aside the needed configuration of rcmcarddav).

**Comment by blind-coder** [comment]
Cool!
I'll try this soon then!

**Comment by phsc** [comment]
Great! Thanks! :+1:

**Comment by ltsavar** [comment]
I tried your composer version but got the error "Fatal error: Class 'Httpful\Bootstrap' not found in /var/www/roundcube/plugins/carddav/carddav_common.php on line 24" right after activation.

**Comment by rumpelsepp** [comment]
Did you actually install the dependencies? https://getcomposer.org/doc/00-intro.md#using-composer

**Comment by ltsavar** [comment]
Hi. Thank for your quick response. I did not use composer befor in my live. so no i did not. i thought its working automagically.

but after doing so it says:
root@mail:/var/www/roundcube/plugins/carddav# composer install
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Nothing to install or update
Generating autoload files

So why is it not installing anything? Am I missing something?
And by the way when switching to composer the install file should say that an extra step is required :)

**Comment by rumpelsepp** [comment]
Maybe the libraries are already there from your previous version?

**Comment by ltsavar** [comment]
My steps where: Install rcmcarddav, but it did not work. Then I found your version. Installed it. Enabling your version with composer got me the error. So there is no other pervious version. The error is still there. 
Vendor Dir looks like this:
root@mail:/var/www/roundcube/plugins/carddav/vendor# ls
autoload.php  bin  composer  nategood  sabre

**Comment by rumpelsepp** [comment]
I am not the creator of this version and I'm just a guy who knows how composer works... :)
Maybe @phsc can help here.

**Comment by ltsavar** [comment]
Ah I see. I guess I'll have to wait then. 
Maybe its a little bug.
Cause vendor/nategood/httpful is allready there and its not going to update.

**Comment by phsc** [comment]
Hm, strange. I did not encounter such a problem, when installing the "composer"-rcmcarddav.
Installing the dependencies is not required for end-users as this version ships with all the needed libraries.

I'll have a look at this.

**Comment by evert** [comment]
I think as a future step, @blind-coder should still consider to make the 'composer install' step for `git clone` users mandatory, so you don't have to keep the `vendor/` directory in the repository. It's kind of a bad practice.

The way we handle this, is that if you're a developer  (and thus need `git clone`) a simple `composer install` should be easy enough, but if you are not a developer, there should be no reason to use an unstable version and you should just install a stable release.

I think it's a bit complicated by the fact that the latest release is nearly a year ago.. but once you are more comfortable doing releases often, it should become less of an issue.

**Comment by rumpelsepp** [comment]
> you don't have to keep the vendor/ directory in the repository. It's kind of a bad practice.

The `composer.lock` file is there the avoid this situation. So :+1: for your comment here.

**Comment by phsc** [comment]
Thanks for your input @evert! Why is it kind of bad practice to keep the vendor directory in the repository? I'm not that much experienced with composer and therefore I'm just curious about that.

**Comment by rumpelsepp** [comment]
composer is a package manager. That means you are supposed to put the depencies of your project into `composer.json` and install them. Composer `creates composer.lock` which includes information about the **exact** revisions of your installed dependencies.

When you decide to update a library you just have to adjust your `composer.lock` and every user is able to update to the same version with composer. It could be seen as some kind of git checkout. It is bad practice to include everything by default because it just clutters your whole repository. You actually only need the revision number and a linkt to fetch it. That's what composer does.

**Comment by evert** [comment]
@phsc it's bad for your version control history. We don't have executable binaries in PHP, but it would be the equivalent of commiting 'compiled binaries' into a VCS.

I think another valid reason is that 'this is how everyone does it' and 'this is what composer recommends',.

Lastly, if you want other people to be able to use rcmcarddav by installing it as a composer dependency, you force these people to install every dependency twice. (once via composer, and once via your own vendor directory).

**Comment by phsc** [comment]
Ok, I see the point.

As @blind-coder is the owner of rcmcarddav, let him decide. Then I will update the pull request.

**Comment by phsc** [comment]
Gently push @blind-coder 

I would love to finish that, as soon as I have your decision, if the dependencies should be part of the repository or not (as recommended).

**Comment by blind-coder** [comment]
Hmm, I think they should NOT be part of the repository, UNLESS it's a release.
I have recently learned several things about git and development with it, so I would like to do it like this:
Do NOT have it in the repository.
But ADD it to the repository when tagging releases (possibly creating a specific release branch for it), so that it can be used by just dropping it into the roundcube/plugins directory.
I would like to keep it as simple for "end-users" as possible.

**Comment by phsc** [comment]
Ok, in this case I will adapt the pull request to NOT include the dependencies.

**Comment by rumpelsepp** [comment]
> But ADD it to the repository when tagging releases (possibly creating a specific release branch for it)

You can e.g. use the github release page and upload release bundles there. :)

**Comment by blind-coder** [comment]
> You can e.g. use the github release page and upload release bundles there. :)

That's a good idea. I was under the impression that tags automatically become available there. Is it also possible to upload files manually?

**Comment by rumpelsepp** [comment]
> That's a good idea. I was under the impression that tags automatically become available there. Is it also possible to upload files manually?

Yeah. There is an automatically created download link for the source code and you can upload as many files you want. It looks like this:

screenshot from 2015-03-26 13-51-35

**Comment by blind-coder** [comment]
Cool, thank you very much! I will use that!

**Comment by evert** [comment]
This is also exactly how we do it. We have a simple build script that creates a clean zip package and also removes all the files that are not interesting for the average user.

https://github.com/fruux/sabre-dav/releases/tag/2.2.0alpha3

**Comment by phsc** [comment]
Superseeded by #94 (sorry, messed up my local repo).

**Pull request closed without merging**
