### PR TITLE
Migrate to composer

### PR DESCRIPTION
**Pull request by phsc**
- do not include /vendor directory in git repository
- some clarifications in INSTALL

### CODE REVIEW

**Comment by phsc** [comment]
Sorry, but I messed up with my local repo (I'm still a newbie...).
Therefore this pull request superseedes #87.

**Comment by phsc** [comment]
I tested this with Roundcube 1.1 and Owncloud 6 (I know, quite old...).
Adding, deleting and modifying contacts worked both ways.

**Comment by blind-coder** [comment]
I have tried this right now, but I get several errors:
Class 'Httpful\\Bootstrap' not found in .../htdocs/plugins/carddav/carddav_common.php on line 26
Class 'Httpful\\Request' not found in .../htdocs/plugins/carddav/carddav_common.php on line 179

Sure that you have everything committed?

**Comment by phsc** [comment]
Yes, I have committed everything. And I use exactly this branch on my productive environment.

I use windows on my computer and after installing PHP and composer, I navigated to the rcmcarddav directory in the command line and ran "composer install" and "composer update". Then composer downloaded all needed files and generated autoload.php. Afterwards I copied this build on my webserver and it worked like a charm.

**Comment by phsc** [comment]
Could you check the "vendor" directory inside rcmcarddav? Are httpful and sabre-vobject correctly downloaded? And do you see autoload.php in the "vendor" directory?

**Comment by blind-coder** [comment]
```text
ll vendor/
total 20
-rw-r--r-- 1 blindcoder blindcoder  183 Mar 29 15:40 autoload.php
drwxr-xr-x 2 blindcoder blindcoder 4096 Mar 29 14:16 bin
drwxr-xr-x 2 blindcoder blindcoder 4096 Mar 29 14:20 composer
drwxr-xr-x 3 blindcoder blindcoder 4096 Mar 29 14:16 nategood
drwxr-xr-x 3 blindcoder blindcoder 4096 Mar 29 14:16 sabre
```

It looks pretty good to me here. However, it seems that the autoload.php is not evaluated here:
```php
require_once 'vendor/autoload.php';
```
Because no matter what I put into it, write_log(), error_log(), even bogus characters that should throw a PHP error, I still get the Httpful\Bootstrap not found error instead of a syntax error.

**Comment by blind-coder** [comment]
Found it. Because of open_basedir I needed to change it to:
```php
require_once __DIR__ . '/vendor/autoload.php';
```

**Comment by blind-coder** [comment]
I have pushed this in a branch feature_composer for now. I'll test it a few days and then if nothing pops up I'll merge it into master.

**Comment by blind-coder** [comment]
Just a short notice:
You have not set an email address in your git config. This breaks several functionalities of git (like git rebase). Please set an email address in the future (even an incorrect one will do).

**Comment by phsc** [comment]
Thank you for pointing this out to me. I was not aware of that.
I've just set the email address.

**Comment by blind-coder** [comment]
I have just merged this into master. Thank you very much!

**Comment by phsc** [comment]
Great! Thank you too!

**Pull request merged**
