### PR TITLE
fix "Class 'Httpful\Bootstrap'" error

### PR DESCRIPTION
**Pull request by blackm**
to avoid the following error:

PHP Fatal error:  Class 'Httpful\Bootstrap' not found in /var/data/www/mydomain_ssl/htdocs/roundcube/plugins/carddav/carddav_common.php on line 25

### CODE REVIEW

**Comment by blind-coder** [comment]
I'm not entirely sure if this is really necessary. composer should pull these in automatically and... I didn't upload a complete archive for the release. I'll fix the latter today, and if you could test that, that would be great!

**Comment by blackm** [comment]
Hi Benjamin,

thanks for looking into this.

Some more details: I updated to roundcube 1.2.3 ..

* downloaded 
https://github.com/roundcube/roundcubemail/releases/download/1.2.3/roundcubemail-1.2.3-complete.tar.gz
* mv roundcube roundcube.bak
* extraced new roundcube and moved to "roundcube"
* copy configuration from roundcube.bak/....
* chown -R www-data:www-data roundcube
* downloaded 
https://github.com/blind-coder/rcmcarddav/releases/tag/v2.0.3
* extraced to my new plugin directory, activated the plugin
* found out roundcube is not working anymore :-(

I hope this will help....

Best regards

Martin



Am 2016-11-30 07:55, schrieb Benjamin Schieder:

**Comment by blind-coder** [comment]
Can you please try the release tar.bz2 or .zip from here and tell me if the issue persists:

https://github.com/blind-coder/rcmcarddav/releases/tag/v2.0.4

**Comment by blackm** [comment]
I did a clean roundcube 1.2.3 installation (just imported my config) and install carddav 2.0.4 --> working, no error message

:-) thanks for fixing this

**Comment by blind-coder** [comment]
Very good, thanks for reporting!

**Pull request closed without merging**
